### ISSUE TITLE
Could you give the specific version of the module used in the code?

### ISSUE THREAD

**Issue by gxxie** [euphoria0-0/Learning-Loss-for-Active-Learning#12]
As mentioned in the title, could you give the specific version of the module used in the code?

**Comment by gxxie** [comment]
The code ran successfully, but there was not enough memory. I just ran the task 'clf', why does the code needs so much memory? The GPU has 16GB of memory.

`RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 15.90 GiB total capacity; 15.04 GiB already allocated; 97.88 MiB free; 15.06 GiB reserved in total by PyTorch)`

**Comment by euphoria0-0** [comment]
@gxxie Hi, thank you for comments.
I haven't met the OOM issue in image classification task, but I'll check it.
I've used GPU with 24GB.

**Comment by gxxie** [comment]
> 
Hello, have you fixed this problem? The codes"Mephisto405/Learning-Loss-for-Active-Learning" you refered I ran successfully. And his codes just need about 2G for running. I think there is something wrong in your codes.
Please help~ I don't have a 24GB graphics card.

**Comment by gxxie** [comment]
> 

Hello, have you fixed this problem? The codes"Mephisto405/Learning-Loss-for-Active-Learning" you refered I ran successfully. And his codes just need about 2G for running. I think there is something wrong in your codes.
Please help~ I don't have a 24GB graphics card.

**Comment by gxxie** [comment]
I ran the program for 4 days, completed the first epoch, and then this error occurred.  
sad
`FileNotFoundError: [Errno 2] No such file or directory: './src/model/ssd_pytorch/VOC.pth'`
